import 'dotenv/config';
import { NestFactory } from '@nestjs/core';
import { AppModule } from '../../src/app.module';
import { PublisherReportDto } from 'src/modules/publisher-report/dto/publisher-report.dto';
import { PrismaService } from '../../src/prisma/prisma.service';
import { PublisherReportService } from 'src/modules/publisher-report/publisher-report.service';

async function bootstrap() {
  console.log('🌱 Ejecutando seed...');

  const app = await NestFactory.createApplicationContext(AppModule);

  const prisma = app.get(PrismaService);
  const publisherReportService = app.get(PublisherReportService);

  const congregation = await prisma.congregation.findFirst({
    where: { name: 'El Esfuerzo' },
  });

  if (!congregation) {
    console.log('Error: La congregación "El Esfuerzo" no existe.');
    return;
  }

  for (const publisherReport of publisherReports) {
    const existingPerson = await prisma.person.findFirst({
      where: {
        first_name: publisherReport.first_name,
        last_name: publisherReport.last_name,
        congregation_id: congregation.id,
      },
      select: {
        id: true,
        first_name: true,
        last_name: true,
      },
    });

    if (existingPerson) {
      const personName = `${existingPerson.first_name} ${existingPerson.last_name}`;
      publisherReport.person_id = existingPerson.id;
      if (publisherReport.first_name) delete publisherReport.first_name;
      if (publisherReport.last_name) delete publisherReport.last_name;
      const existsPublisherReport = await prisma.publisherReport.findFirst({
        where: {
          person_id: publisherReport.person_id,
          service_year: publisherReport.service_year,
          year: publisherReport.year,
          month: publisherReport.month,
        },
      });
      if (existsPublisherReport) {
        console.log(`ℹ️ El reporte para ${existingPerson.id} ${personName} ya existe.`);
        continue;
      }
      await publisherReportService.create(publisherReport as PublisherReportDto);
      console.log(`✅ Reporte creado para ${existingPerson.id} ${personName}`);
    } else {
      console.log(`⛔ "${publisherReport.first_name} ${publisherReport.last_name}" no se encontró.`);
    }
  }

  console.log('✅ Seed completado correctamente');

  await app.close();
}

bootstrap().catch((error) => {
  console.error('❌ Error ejecutando seed:', error);
  process.exit(1);
});

const publisherReports: (PublisherReportDto & { first_name?: string; last_name?: string })[] = [
  {
    person_id: 0,
    first_name: 'Maryoris',
    last_name: 'Ariza',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Jesus Maria',
    last_name: 'De Las Salas Jimenez',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'José Manuel',
    last_name: 'De Las Salas Jimenez',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Johan David',
    last_name: 'Rodriguez Ariza',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Daniel Eduardo',
    last_name: 'Almagro Hurtado',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 1,
    is_auxiliary_pioneer: true,
    hours: 16,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Soraya',
    last_name: 'De Las Salas Jimenez',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Ivanna Patricia',
    last_name: 'Miranda De Cervantes',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Jonathan',
    last_name: 'Romero',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Libardo',
    last_name: 'Romero',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Yanine Paola',
    last_name: 'Romero Perez',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 1,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Abner Enrique',
    last_name: 'Tovar Barraza',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Maribella',
    last_name: 'Tovar Mejia',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Maurilia',
    last_name: 'Romero Carvajal',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 1,
    is_auxiliary_pioneer: false,
    hours: 49,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Shalimar Paola',
    last_name: 'Almagro Rios',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 47,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Audreys Carolina',
    last_name: 'Martinez Guzman',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 4,
    is_auxiliary_pioneer: false,
    hours: 26,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Melissa',
    last_name: 'Ochoa Cepeda',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 1,
    is_auxiliary_pioneer: true,
    hours: 16,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Marelvis',
    last_name: 'Rodriguez',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Beatriz Elena',
    last_name: 'Romero Gamarra',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Elsa',
    last_name: 'Bustamante De Rodriguez',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Gerson',
    last_name: 'Cervantes Caballero',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 2,
    is_auxiliary_pioneer: true,
    hours: 16,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Valery',
    last_name: 'Cervantes Doncel',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: true,
    hours: 16,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Lizeth Johanna',
    last_name: 'Fabregas',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Delfa',
    last_name: 'Nieto',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Marlene Esther',
    last_name: 'Nieto De Vega',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 1,
    is_auxiliary_pioneer: true,
    hours: 16,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Jimmy Manuel',
    last_name: 'Ochoa Villalba',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 2,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Rosario Esther',
    last_name: 'Nieto De Vega',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 2,
    is_auxiliary_pioneer: false,
    hours: 55,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Cristian',
    last_name: 'Osorio Rodriguez',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 2,
    is_auxiliary_pioneer: false,
    hours: 30,
    notes: 'LDC: 5 horas',
  },
  {
    person_id: 0,
    first_name: 'Janerlee',
    last_name: 'Osorio Doncel',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 3,
    is_auxiliary_pioneer: false,
    hours: 44,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Edilberto Manuel',
    last_name: 'Carrillo Sanmartin',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Keilly',
    last_name: 'Carrillo',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Yudis Del Carmen',
    last_name: 'De La Cruz',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 5,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Yomais Judith',
    last_name: 'Gonzalez',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Juan Esteban',
    last_name: 'Marin Gonzalez',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: true,
    hours: 18,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Luis Andres',
    last_name: 'Marin Gonzalez',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 40,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Nelson',
    last_name: 'Angulo',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 3,
    is_auxiliary_pioneer: false,
    hours: 70,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Josefina',
    last_name: 'Carrillo',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 6,
    is_auxiliary_pioneer: false,
    hours: 51,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Sebastian Andres',
    last_name: 'Gonzalez',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 1,
    is_auxiliary_pioneer: false,
    hours: 54,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'John Enrique',
    last_name: 'Huerta Arce',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 2,
    is_auxiliary_pioneer: false,
    hours: 48,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Tamar Eugenia',
    last_name: 'Huerta',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 10,
    is_auxiliary_pioneer: false,
    hours: 45,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Andres Enrique',
    last_name: 'Marin Gonzalez',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 47,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Ana Cristina',
    last_name: 'Ochoa Cepeda',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 2,
    is_auxiliary_pioneer: false,
    hours: 40,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Angel Custodio',
    last_name: 'Ariza Herrera',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Abner Enrique',
    last_name: 'Tovar Barraza',
    service_year: 2026,
    year: 2025,
    month: 10,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Elsa',
    last_name: 'Yepes',
    service_year: 2026,
    year: 2025,
    month: 12,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Jesús David',
    last_name: 'Romero',
    service_year: 2026,
    year: 2025,
    month: 12,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
  {
    person_id: 0,
    first_name: 'Jesús Miguel',
    last_name: 'Rodriguez',
    service_year: 2026,
    year: 2025,
    month: 12,
    participated: true,
    bible_courses: 0,
    is_auxiliary_pioneer: false,
    hours: 0,
    notes: '',
  },
];
