import 'dotenv/config';
import { NestFactory } from '@nestjs/core';
import { AppModule } from '../../src/app.module';
import { TeamService } from '../../src/modules/team/team.service';
import { PersonService } from '../../src/modules/person/person.service';
import { PrismaService } from '../../src/prisma/prisma.service';
import { PersonDto } from 'src/modules/person/dto/person.dto';

async function bootstrap() {
  console.log('🌱 Ejecutando seed...');

  const app = await NestFactory.createApplicationContext(AppModule);

  const prisma = app.get(PrismaService);
  const personService = app.get(PersonService);

  const congregation = await prisma.congregation.findFirst({
    where: { name: 'El Esfuerzo' },
  });

  if (!congregation) {
    console.log('Error: La congregación "El Esfuerzo" no existe.');
    return;
  }

  for (const personData of people) {
    const existingPerson = await prisma.person.findFirst({
      where: {
        first_name: personData.first_name,
        last_name: personData.last_name,
        congregation_id: congregation.id,
      },
    });

    if (!existingPerson) {
      personData.congregation_id = congregation.id;
      personData.is_special_pioneer = false;
      personData.is_field_missionary = false;
      personData.is_anointed = false;
      await personService.create(personData as PersonDto);
      console.log(`✅ Persona creada: ${personData.first_name} ${personData.last_name}`);
    } else {
      console.log(`ℹ️ La persona "${personData.first_name} ${personData.last_name}" ya existe.`);
    }
  }

  console.log('✅ Seed completado correctamente');

  await app.close();
}

bootstrap().catch((error) => {
  console.error('❌ Error ejecutando seed:', error);
  process.exit(1);
});

const people: Partial<PersonDto>[] = [
  {
    team_id: 1,
    first_name: 'Angel Custodio',
    last_name: 'Ariza Herrera',
    birth_date: new Date('1969-12-16'),
    baptism_date: new Date('2007-07-01'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: true,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 1,
    first_name: 'Maryoris',
    last_name: 'Ariza',
    birth_date: new Date('1980-05-30'),
    baptism_date: new Date('2023-06-23'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 1,
    first_name: 'Jesus Maria',
    last_name: 'De Las Salas Jimenez',
    birth_date: new Date('1948-09-12'),
    baptism_date: new Date('2010-07-04'),
    sex: 'MALE',
    is_elder: true,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 1,
    first_name: 'José Manuel',
    last_name: 'De Las Salas Jimenez',
    birth_date: new Date('1969-07-10'),
    baptism_date: new Date('2018-06-16'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 1,
    first_name: 'Edith',
    last_name: 'Quintero',
    birth_date: new Date('1961-08-15'),
    baptism_date: undefined,
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 1,
    first_name: 'Johan',
    last_name: 'Rodriguez',
    birth_date: new Date('2013-10-09'),
    baptism_date: undefined,
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 1,
    first_name: 'Jhulian',
    last_name: 'Rodriguez',
    birth_date: new Date('2009-11-28'),
    baptism_date: undefined,
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
    is_active: false,
  },
  {
    team_id: 2,
    first_name: 'Daniel Eduardo',
    last_name: 'Almagro Hurtado',
    birth_date: new Date('2000-11-22'),
    baptism_date: new Date('2011-02-05'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: true,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 2,
    first_name: 'Soraya',
    last_name: 'De Las Salas Jimenez',
    birth_date: new Date('1971-05-15'),
    baptism_date: new Date('2012-07-14'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 2,
    first_name: 'Ivanna Patricia',
    last_name: 'Miranda De Cervantes',
    birth_date: new Date('1977-06-13'),
    baptism_date: new Date('2002-09-14'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 2,
    first_name: 'Mary',
    last_name: 'Rodriguez',
    birth_date: new Date(),
    baptism_date: new Date('2023-06-24'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 2,
    first_name: 'Jonathan',
    last_name: 'Romero',
    birth_date: new Date('1988-09-09'),
    baptism_date: new Date('2025-10-11'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 2,
    first_name: 'Libardo',
    last_name: 'Romero',
    birth_date: new Date('1964-06-24'),
    baptism_date: undefined,
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: false,
    is_anointed: false,
  },
  {
    team_id: 2,
    first_name: 'Jesús David',
    last_name: 'Romero',
    birth_date: new Date('2012-01-01'),
    baptism_date: undefined,
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: false,
    is_anointed: false,
  },
  {
    team_id: 2,
    first_name: 'Yanine Paola',
    last_name: 'Romero Perez',
    birth_date: new Date('1990-12-15'),
    baptism_date: new Date('2023-06-24'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 2,
    first_name: 'Jeyfren',
    last_name: 'Sotaquirá',
    birth_date: new Date(),
    baptism_date: new Date('2023-06-24'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 2,
    first_name: 'Abner Enrique',
    last_name: 'Tovar Barraza',
    birth_date: new Date('1999-11-06'),
    baptism_date: new Date('2021-04-22'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: true,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 2,
    first_name: 'Maribella',
    last_name: 'Tovar Mejia',
    birth_date: new Date('2004-08-30'),
    baptism_date: new Date('2023-07-02'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 2,
    first_name: 'Maurilia',
    last_name: 'Romero Carvajal',
    birth_date: new Date('1964-09-15'),
    baptism_date: new Date('1998-06-30'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: true,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 2,
    first_name: 'Shalimar Paola',
    last_name: 'Almagro Rios',
    birth_date: new Date('1998-12-27'),
    baptism_date: new Date('2013-11-02'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: true,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 2,
    first_name: 'Audreys Carolina',
    last_name: 'Martinez Guzman',
    birth_date: new Date('1997-06-05'),
    baptism_date: new Date('2019-03-16'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: true,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Melissa',
    last_name: 'Ochoa Cepeda',
    birth_date: new Date('1980-08-28'),
    baptism_date: new Date('1995-01-15'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Ana Cristina',
    last_name: 'Ochoa Cepeda',
    birth_date: new Date('2004-03-17'),
    baptism_date: new Date('2015-01-11'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: true,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Marelvis',
    last_name: 'Rodriguez',
    birth_date: new Date('1975-09-25'),
    baptism_date: new Date('1994-01-13'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Jesús Miguel',
    last_name: 'Rodriguez',
    birth_date: new Date('2019-01-01'),
    baptism_date: undefined,
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Yudis Del Carmen',
    last_name: 'De La Cruz',
    birth_date: new Date('1979-05-07'),
    baptism_date: new Date('2014-06-07'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
    is_active: false,
  },
  {
    team_id: 3,
    first_name: 'Wilmer',
    last_name: 'Barrios',
    birth_date: new Date('1975-01-01'),
    baptism_date: new Date('2010-01-01'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Beatriz Elena',
    last_name: 'Romero Gamarra',
    birth_date: new Date('1940-03-10'),
    baptism_date: new Date('1987-01-10'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Elsa',
    last_name: 'Bustamante De Rodriguez',
    birth_date: new Date('1955-12-30'),
    baptism_date: new Date('1992-01-19'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Gerson',
    last_name: 'Cervantes Caballero',
    birth_date: new Date('1996-09-01'),
    baptism_date: new Date('2019-07-20'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: true,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Valery',
    last_name: 'Cervantes Doncel',
    birth_date: new Date('1995-02-20'),
    baptism_date: new Date('2018-12-15'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Lizeth Johanna',
    last_name: 'Fabregas',
    birth_date: new Date('1992-04-15'),
    baptism_date: new Date('2006-12-21'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Delfa',
    last_name: 'Nieto',
    birth_date: new Date('1940-08-14'),
    baptism_date: new Date('1991-03-14'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Marlene Esther',
    last_name: 'Nieto De Vega',
    birth_date: new Date('1964-06-19'),
    baptism_date: new Date('2002-09-09'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Jimmy Manuel',
    last_name: 'Ochoa Villalba',
    birth_date: new Date('1978-07-22'),
    baptism_date: new Date('1996-07-20'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: true,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Rosario Esther',
    last_name: 'Nieto De Vega',
    birth_date: new Date('1960-03-12'),
    baptism_date: new Date('1998-02-15'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: true,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Cristian',
    last_name: 'Osorio Rodriguez',
    birth_date: new Date('1997-10-01'),
    baptism_date: new Date('2019-02-02'),
    sex: 'MALE',
    is_elder: true,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 3,
    first_name: 'Janerlee',
    last_name: 'Osorio Doncel',
    birth_date: new Date('1996-12-05'),
    baptism_date: new Date('2018-12-15'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: true,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 4,
    first_name: 'Edilberto',
    last_name: 'Carrillo Sanmartin',
    birth_date: new Date('1961-06-22'),
    baptism_date: new Date('1978-07-29'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 4,
    first_name: 'Keilly',
    last_name: 'Carrillo',
    birth_date: new Date('1984-11-12'),
    baptism_date: new Date('1995-01-15'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 4,
    first_name: 'Yudis Del Carmen',
    last_name: 'De La Cruz',
    birth_date: new Date('1979-04-07'),
    baptism_date: new Date('2014-06-07'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 4,
    first_name: 'Yomais Judith',
    last_name: 'Gonzalez',
    birth_date: new Date('1979-10-12'),
    baptism_date: new Date('2024-11-02'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 4,
    first_name: 'Juan Esteban',
    last_name: 'Marin Gonzalez',
    birth_date: new Date('2012-08-23'),
    baptism_date: new Date('2024-11-02'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 4,
    first_name: 'Luis Andres',
    last_name: 'Marin Gonzalez',
    birth_date: new Date('2009-04-26'),
    baptism_date: new Date('2024-11-02'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: true,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 4,
    first_name: 'Nelson',
    last_name: 'Angulo',
    birth_date: new Date('1943-03-17'),
    baptism_date: new Date('1983-10-01'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: true,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 4,
    first_name: 'Josefina',
    last_name: 'Carrillo',
    birth_date: new Date('1959-01-15'),
    baptism_date: new Date('1976-07-29'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: true,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 4,
    first_name: 'Sebastian Andres',
    last_name: 'Gonzalez',
    birth_date: new Date('2006-07-18'),
    baptism_date: new Date('2023-10-21'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: true,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 4,
    first_name: 'John Enrique',
    last_name: 'Huerta Arce',
    birth_date: new Date('1982-07-06'),
    baptism_date: new Date('2001-01-13'),
    sex: 'MALE',
    is_elder: true,
    is_ministerial_servant: false,
    is_regular_pioneer: false,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 4,
    first_name: 'Tamar Eugenia',
    last_name: 'Huerta',
    birth_date: new Date('1992-09-29'),
    baptism_date: new Date('2008-08-20'),
    sex: 'FEMALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: true,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 4,
    first_name: 'Andres Enrique',
    last_name: 'Marin Gonzalez',
    birth_date: new Date('2002-06-18'),
    baptism_date: new Date('2024-11-02'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: true,
    is_other_sheep: true,
    is_anointed: false,
  },
  {
    team_id: 4,
    first_name: 'Andres Enrique',
    last_name: 'Marin Gonzalez',
    birth_date: new Date('2002-06-18'),
    baptism_date: new Date('2024-11-02'),
    sex: 'MALE',
    is_elder: false,
    is_ministerial_servant: false,
    is_regular_pioneer: true,
    is_other_sheep: true,
    is_anointed: false,
  },
];
