import 'dotenv/config';
import { NestFactory } from '@nestjs/core';
import { AppModule } from '../../../src/app.module';
import { PersonService } from '../../../src/modules/person/person.service';
import { PrismaService } from '../../../src/prisma/prisma.service';
import { PersonDto } from '../../../src/modules/person/dto/person.dto';

async function bootstrap() {
  console.log('🌱 Ejecutando seed...');

  const app = await NestFactory.createApplicationContext(AppModule);

  const prisma = app.get(PrismaService);
  const personService = app.get(PersonService);

  const congregation = await prisma.congregation.findFirst({
    where: { name: 'Norte De Malambo' },
  });

  if (!congregation) {
    console.log('Error: La congregación "Norte De Malambo" no existe.');
    return;
  }

  const teams = await prisma.team.findMany({
    where: { congregation_id: congregation.id },
  });

  if (!teams) {
    console.log('Error: No se encontraron grupos para la congregación "Norte De Malambo".');
    return;
  }

  const teamIdByName: Map<string, number> = new Map();
  for (const team of teams) {
    teamIdByName.set(team.name, team.id);
  }

  let count = 0;

  for (const personData of people) {
    const existingPerson = await prisma.person.findFirst({
      where: {
        first_name: personData.first_name,
        last_name: personData.last_name,
        congregation_id: congregation.id,
      },
    });

    if (!existingPerson) {
      personData.congregation_id = congregation.id;
      personData.team_id = teamIdByName.get(personData.team);
      personData.is_active = true;

      if (personData.birth_date) personData.birth_date = new Date(personData.birth_date);
      if (personData.baptism_date) personData.baptism_date = new Date(personData.baptism_date);

      if (personData.sex === 'Hombre') personData.sex = 'MALE';
      else personData.sex = 'FEMALE';

      if (personData.is_special_pioneer === 'Sí') personData.is_special_pioneer = true;
      else personData.is_special_pioneer = false;

      if (personData.is_field_missionary === 'Sí') personData.is_field_missionary = true;
      else personData.is_field_missionary = false;

      if (personData.is_anointed === 'Sí') personData.is_anointed = true;
      else personData.is_anointed = false;

      if (personData.is_elder === 'Sí') personData.is_elder = true;
      else personData.is_elder = false;

      if (personData.is_ministerial_servant === 'Sí') personData.is_ministerial_servant = true;
      else personData.is_ministerial_servant = false;

      if (personData.is_regular_pioneer === 'Sí') personData.is_regular_pioneer = true;
      else personData.is_regular_pioneer = false;

      if (personData.is_other_sheep === 'Sí') personData.is_other_sheep = true;
      else personData.is_other_sheep = false;

      delete personData.team;

      await personService.create(personData as PersonDto);
      console.log(`✅ Persona creada: ${personData.first_name} ${personData.last_name}`);
    } else {
      console.log(`ℹ️ La persona "${personData.first_name} ${personData.last_name}" ya existe.`);
    }
  }

  console.log('✅ Seed completado correctamente');

  await app.close();
}

bootstrap().catch((error) => {
  console.error('❌ Error ejecutando seed:', error);
  process.exit(1);
});

const people: any[] = [
  {
    first_name: 'Erika',
    last_name: 'Jimenez Raad',
    birth_date: '1982-09-06',
    baptism_date: '2025-02-02',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Efrain',
    last_name: 'Reales Mendez',
    birth_date: '2005-08-22',
    baptism_date: '2005-04-04',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Demostenes',
    last_name: 'Reynel Zetuain',
    birth_date: '1955-03-29',
    baptism_date: '2019-07-13',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'Sí',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Manuel Fernando',
    last_name: 'Ochoa Villalba',
    birth_date: '1973-01-05',
    baptism_date: '1996-06-20',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Ladys Esther',
    last_name: 'Mendoza De Romero',
    birth_date: '1950-04-05',
    baptism_date: '1991-03-19',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Karen',
    last_name: 'Arrieta Cheg',
    birth_date: '1985-08-27',
    baptism_date: '2016-01-11',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Dalia',
    last_name: 'Muñoz De La Cruz',
    birth_date: '1971-02-18',
    baptism_date: '2019-07-13',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Angela Nicoll',
    last_name: 'Cacua Arrieta',
    birth_date: '2009-08-15',
    baptism_date: '2024-03-16',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Aceneth',
    last_name: 'Pava',
    birth_date: '1947-05-23',
    baptism_date: '1994-07-04',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Josefa',
    last_name: 'Peñaranda Villafañe',
    birth_date: '1981-10-29',
    baptism_date: '1998-07-29',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Matias David',
    last_name: 'Cantillo Meza',
    birth_date: '2014-01-28',
    baptism_date: null,
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Nelvis',
    last_name: 'Suarez Martinez',
    birth_date: '1990-04-06',
    baptism_date: null,
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Yolanda',
    last_name: 'Gelvis Navarro',
    birth_date: '1959-04-25',
    baptism_date: '2000-01-10',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Walter',
    last_name: 'Reales De Avila',
    birth_date: '1973-08-23',
    baptism_date: '2021-04-04',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Walter David',
    last_name: 'Reales Mendez',
    birth_date: '2008-03-12',
    baptism_date: '2021-04-04',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Sara',
    last_name: 'Raad De Jimenez',
    birth_date: '1961-09-02',
    baptism_date: '1995-07-01',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Gledys',
    last_name: 'Mendez De Reales',
    birth_date: '1978-05-07',
    baptism_date: '2021-03-10',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Margarita Rosa',
    last_name: 'Cardenas',
    birth_date: '1968-08-07',
    baptism_date: '2008-02-02',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Luis Alberto',
    last_name: 'Quintero Florez',
    birth_date: '1958-03-10',
    baptism_date: '2001-04-12',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Gladys Ester',
    last_name: 'Coba Peña',
    birth_date: '1958-06-08',
    baptism_date: '2025-10-11',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Ovidio Antonio',
    last_name: 'De La Cruz',
    birth_date: '1958-02-23',
    baptism_date: '1986-01-03',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'Sí',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Nayibe Ester',
    last_name: 'Tejeda Martinez',
    birth_date: '1968-03-08',
    baptism_date: null,
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Maria',
    last_name: 'Moreno De Martinez',
    birth_date: '1957-06-20',
    baptism_date: '1985-12-28',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Isabel Judith',
    last_name: 'Castro Barrios',
    birth_date: '1952-07-31',
    baptism_date: '1990-06-30',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Humberto',
    last_name: 'Martinez Mercado',
    birth_date: '1946-06-30',
    baptism_date: '1985-01-05',
    sex: 'Hombre',
    is_elder: 'Sí',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Cristian',
    last_name: 'Cordoba Monsalve',
    birth_date: '1994-10-16',
    baptism_date: '2013-01-19',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Alba Liria',
    last_name: 'Monsalve Atehurtua',
    birth_date: '1959-05-12',
    baptism_date: '2006-09-16',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Julia',
    last_name: 'De La Rosa Hernandez',
    birth_date: '1982-07-22',
    baptism_date: '2000-01-10',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Juan Esteban',
    last_name: 'De La Rosa Hernandez',
    birth_date: '2007-12-14',
    baptism_date: '2023-01-14',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Carmen Maritza',
    last_name: 'Perez Nieto',
    birth_date: '1955-08-07',
    baptism_date: '1996-02-04',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'David Alfonzo',
    last_name: 'Amado Orozco',
    birth_date: '1989-02-23',
    baptism_date: '2015-09-05',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Jorge Elias',
    last_name: 'Beyet Freyle',
    birth_date: '1957-10-02',
    baptism_date: '2014-08-02',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'Sí',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Margarita',
    last_name: 'Perez',
    birth_date: '1968-10-25',
    baptism_date: '1998-08-23',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Alba',
    last_name: 'Armella Vargas',
    birth_date: '1955-01-11',
    baptism_date: '2010-01-10',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Margarita',
    last_name: 'Salinas Sanchez',
    birth_date: '1961-06-28',
    baptism_date: 'JULIO DE 1987',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Albanis',
    last_name: 'Hernandez Camacho',
    birth_date: '1964-09-12',
    baptism_date: '1994-01-10',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Wilman',
    last_name: 'Gonzales Jimenez',
    birth_date: '1967-10-20',
    baptism_date: '1991-03-18',
    sex: 'Hombre',
    is_elder: 'Sí',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Kelly Cecilia',
    last_name: 'Orozco Camargo',
    birth_date: '1984-09-29',
    baptism_date: '1999-07-05',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Jheiner',
    last_name: 'Jimenez',
    birth_date: '2004-02-14',
    baptism_date: '2023-07-24',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Grisy Margarita',
    last_name: 'Ballestas Lara',
    birth_date: '1984-08-05',
    baptism_date: '2024-11-02',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Daniela',
    last_name: 'Gutierrez Ballestas',
    birth_date: '2013-09-09',
    baptism_date: null,
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Alexandra',
    last_name: 'Mendez Orozco',
    birth_date: '2014-10-29',
    baptism_date: null,
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Alexander',
    last_name: 'Mendez Salinas',
    birth_date: '1981-08-20',
    baptism_date: '1998-07-20',
    sex: 'Hombre',
    is_elder: 'Sí',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Margaret',
    last_name: 'Perez Vasquez',
    birth_date: '1978-03-23',
    baptism_date: '1994-09-30',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Boris Alfonzo',
    last_name: 'Pareja Almarales',
    birth_date: '1967-06-22',
    baptism_date: '2004-01-10',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Maria Claudia',
    last_name: 'Peñaranda',
    birth_date: '1972-05-10',
    baptism_date: '1991-06-05',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Misael',
    last_name: 'San Juan Rizo',
    birth_date: '1969-02-07',
    baptism_date: '1999-09-12',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'Sí',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Keila',
    last_name: 'Vega Espejo',
    birth_date: '1975-12-29',
    baptism_date: '1996-03-09',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Iginio Dionisio',
    last_name: 'Molina',
    birth_date: '1974-12-26',
    baptism_date: '1989-01-07',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Emilse Judit',
    last_name: 'Mendoza Ayala',
    birth_date: '1963-07-16',
    baptism_date: '2004-01-10',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Aslly Mishel',
    last_name: 'Molina Perez',
    birth_date: '2009-03-11',
    baptism_date: '2018-07-01',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Arelys Maria',
    last_name: 'Blanco De Posada',
    birth_date: '1955-09-05',
    baptism_date: '2025-10-11',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Luisa',
    last_name: 'Morales De Gutierrez',
    birth_date: '1971-02-14',
    baptism_date: '2020-03-08',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Alexander Alfonzo',
    last_name: 'Gutierrez Viloria',
    birth_date: '1971-04-10',
    baptism_date: '2020-07-30',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Alcides De Jesus',
    last_name: 'Garcia Ibañez',
    birth_date: '1966-07-13',
    baptism_date: '2025-10-11',
    sex: 'Hombre',
    is_elder: 'Sí',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Luz Adriana',
    last_name: 'Muñeton',
    birth_date: '1971-01-25',
    baptism_date: '2008-02-02',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Sharon',
    last_name: 'Jarava Mendez',
    birth_date: '2010-03-02',
    baptism_date: '2025-10-11',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Maria Lourdes',
    last_name: 'Peña De Gonzales',
    birth_date: '1955-07-04',
    baptism_date: '1996-03-14',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Leida Lucia',
    last_name: 'Mendez Salinas',
    birth_date: '1984-06-16',
    baptism_date: '1997-07-20',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Larry Joel',
    last_name: 'Jarava Mendez',
    birth_date: '2016-08-04',
    baptism_date: null,
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Hector Enrique',
    last_name: 'Gonzales Espinosa',
    birth_date: '1954-06-03',
    baptism_date: '1996-03-14',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'Sí',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Marcos Alberto',
    last_name: 'Rojas Salgado',
    birth_date: '1961-01-19',
    baptism_date: '1993-01-16',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Nadia Patricia',
    last_name: 'Amaya De Rojas',
    birth_date: '1980-12-30',
    baptism_date: '2007-01-06',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Luzmila Emilse',
    last_name: 'Toscano Veleño',
    birth_date: '1951-09-09',
    baptism_date: '1997-07-04',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Julio Cesar',
    last_name: 'Madrid Olivares',
    birth_date: '2004-06-09',
    baptism_date: '2014-06-01',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Jaime Jesus',
    last_name: 'Barandica Torres',
    birth_date: '1961-04-17',
    baptism_date: '2003-12-01',
    sex: 'Hombre',
    is_elder: 'Sí',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Hernando Jose',
    last_name: 'Posada Cajal',
    birth_date: '1955-04-04',
    baptism_date: '2000-07-08',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Erlys Isabel',
    last_name: 'Madrid Olivares',
    birth_date: '2001-12-26',
    baptism_date: '2014-06-01',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Dina Luz',
    last_name: 'Villar',
    birth_date: '1992-02-03',
    baptism_date: '2025-02-02',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Modesto Antonio',
    last_name: 'Torres Fontalvo',
    birth_date: '1946-02-10',
    baptism_date: '2016-05-08',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Liliana',
    last_name: 'Alvarado',
    birth_date: '1969-10-23',
    baptism_date: '1988-03-27',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Eduardo Jose',
    last_name: 'Velez Alvarado',
    birth_date: '2002-12-09',
    baptism_date: '2014-06-29',
    sex: 'Hombre',
    is_elder: 'Sí',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Carolina Andrea',
    last_name: 'Narvaez Alvarado',
    birth_date: '1997-11-14',
    baptism_date: '2010-10-23',
    sex: 'Mujer',
    is_elder: 'Sí',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Doris Elena',
    last_name: 'Martinez De Gonzales',
    birth_date: '1953-09-05',
    baptism_date: '2014-01-04',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Ana',
    last_name: 'Villeros Garcia',
    birth_date: '1965-07-17',
    baptism_date: '2011-07-16',
    sex: 'Mujer',
    is_elder: 'Sí',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Fernanda',
    last_name: 'Vasquez',
    birth_date: '2000-01-01',
    baptism_date: null,
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Luis',
    last_name: 'Vasquez',
    birth_date: '1995-07-31',
    baptism_date: '2022-03-13',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Yovany',
    last_name: 'Ballestas Diaz',
    birth_date: '2002-01-01',
    baptism_date: '2014-10-05',
    sex: 'Hombre',
    is_elder: 'Sí',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Keiviz Dario',
    last_name: 'De Moya Gonzales',
    birth_date: '1987-08-27',
    baptism_date: '2017-06-10',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Gelen',
    last_name: 'Morales Arroyo',
    birth_date: '2005-07-01',
    baptism_date: '2025-02-02',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Fabian Alonzo',
    last_name: 'De La Hoz',
    birth_date: '1981-12-02',
    baptism_date: '2008-12-23',
    sex: 'Ambos',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Claudia',
    last_name: 'Perez De La Hoz',
    birth_date: '1975-10-30',
    baptism_date: '1989-11-11',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Carlos Enrique',
    last_name: 'Luna Herrera',
    birth_date: '1961-11-11',
    baptism_date: '1975-09-04',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Angie',
    last_name: 'Cera Julio',
    birth_date: '1994-12-27',
    baptism_date: '2012-03-03',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Adalgiza',
    last_name: 'Arroyo',
    birth_date: '1982-01-29',
    baptism_date: '2025-02-02',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'No',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Nuris Del Carmen',
    last_name: 'Torres Santana',
    birth_date: '1951-07-07',
    baptism_date: '1993-01-16',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Nancy',
    last_name: 'Barrera De Rojas',
    birth_date: '1956-08-01',
    baptism_date: '1984-05-01',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Monica',
    last_name: 'Hurtado Doria',
    birth_date: '1975-09-04',
    baptism_date: '1989-01-07',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Mayra Alejandra',
    last_name: 'Fontalvo',
    birth_date: '1976-11-19',
    baptism_date: '2000-03-04',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Martha',
    last_name: 'Pastor De Vargas',
    birth_date: '1959-01-26',
    baptism_date: '1975-12-20',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Marina',
    last_name: 'Sanjuan De Plata',
    birth_date: '1962-07-08',
    baptism_date: '2000-10-02',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Maria Fernanda',
    last_name: 'Ochoa Miranda',
    birth_date: '2003-06-22',
    baptism_date: '2015-09-05',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Laura Camila',
    last_name: 'Sanjuan Vega',
    birth_date: '2009-11-20',
    baptism_date: '2019-06-15',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Gladys Esther',
    last_name: 'Castro Barrios',
    birth_date: '1950-10-11',
    baptism_date: '1988-05-27',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Elvia Janet',
    last_name: 'Salinas Sanchez',
    birth_date: '1968-06-16',
    baptism_date: '1985-05-03',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Doris Elena',
    last_name: 'Gonzales Martinez',
    birth_date: '1982-10-04',
    baptism_date: '2003-01-12',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Denya Isabel',
    last_name: 'Gonzales Fontalvo',
    birth_date: '2009-12-11',
    baptism_date: '2019-10-14',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Daneis Cecilia',
    last_name: 'Gonzales Fontalvo',
    birth_date: '2007-02-02',
    baptism_date: '2019-10-14',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 3',
  },
  {
    first_name: 'Cesar Alfonzo',
    last_name: 'Rojas Velazques',
    birth_date: '1948-08-31',
    baptism_date: '2007-01-07',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 4',
  },
  {
    first_name: 'Ariel',
    last_name: 'Almagro Hurtado',
    birth_date: '1974-07-22',
    baptism_date: '2010-01-11',
    sex: 'Hombre',
    is_elder: 'Sí',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Ana Maria',
    last_name: 'Miranda Ochoa',
    birth_date: '1982-10-07',
    baptism_date: '1997-09-12',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Amparo Cecilia',
    last_name: 'Rivera Rodriguez',
    birth_date: '1952-08-07',
    baptism_date: '2010-10-01',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Fernando Alonzo',
    last_name: 'Ochoa Miranda',
    birth_date: '2006-10-11',
    baptism_date: '2015-09-05',
    sex: 'Hombre',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Adriana Melissa',
    last_name: 'Alvarado',
    birth_date: '1996-09-23',
    baptism_date: '2007-11-03',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Deyanira Esther',
    last_name: 'Paez De Meza',
    birth_date: '1970-07-15',
    baptism_date: '2019-07-13',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 1',
  },
  {
    first_name: 'Dagoberto Antonio',
    last_name: 'Alvarado',
    birth_date: '1940-08-22',
    baptism_date: '1988-03-26',
    sex: 'Hombre',
    is_elder: 'Sí',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
  {
    first_name: 'Rita',
    last_name: 'Amaya Orozco Santana',
    birth_date: '1955-01-05',
    baptism_date: '1972-08-18',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'No',
    is_anointed: 'No',
    team: 'Grupo 2',
  },
  {
    first_name: 'Paola Ines',
    last_name: 'Anaya Palencia',
    birth_date: '1962-02-04',
    baptism_date: '1996-12-16',
    sex: 'Mujer',
    is_elder: 'No',
    is_ministerial_servant: 'No',
    is_regular_pioneer: 'Sí',
    is_special_pioneer: 'No',
    is_field_missionary: 'No',
    is_other_sheep: 'Sí',
    is_anointed: 'No',
    team: 'Grupo 5',
  },
];
